// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Tue Jul 28 16:19:15 2020

MIXER_COEFFICENTS MIXER_COEFFICENTS_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.nRST(nRST_sig) ,	// input  nRST_sig
	.latch_input(latch_input_sig) ,	// input  latch_input_sig
	.coefficent_input(coefficent_input_sig) ,	// input [15:0] coefficent_input_sig
	.input_address(input_address_sig) ,	// input [3:0] input_address_sig
	.output_address(output_address_sig) ,	// input [3:0] output_address_sig
	.config_id(config_id_sig) ,	// input [3:0] config_id_sig
	.coeff_a(coeff_a_sig) ,	// output [15:0] coeff_a_sig
	.coeff_b(coeff_b_sig) ,	// output [15:0] coeff_b_sig
	.coeff_c(coeff_c_sig) ,	// output [15:0] coeff_c_sig
	.coeff_d(coeff_d_sig) ,	// output [15:0] coeff_d_sig
	.coeff_e(coeff_e_sig) ,	// output [15:0] coeff_e_sig
	.coeff_f(coeff_f_sig) ,	// output [15:0] coeff_f_sig
	.coeff_output(coeff_output_sig) 	// output [15:0] coeff_output_sig
);

